ame: calval-netops
channels:
    - conda-forge
dependencies:
    - python=3.9
    - jupyter
    - notebook
    - jupyterlab
    - jupyter-book
    - gdal
    - numpy
    - scipy
    - pandas
    - matplotlib
    - geopandas
    - pathlib
    - scikit-learn
    - mystmd
    - jupyterlab-myst
    - bokeh
    - pip
    - opencv
    - pip:
        - git+https://github.com/hectornieto/airborne_tools
