name: calval-netops
channels:
    - conda-forge
dependencies:
    - jupyter
    - notebook
    - jupyterlab
    - jupyter-book
    - jupyterlab-myst
    - gdal
    - numpy
    - scipy
    - pandas
    - matplotlib
    - geopandas
    - pathlib
    - scikit-learn
    - pip
